# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wordpressazapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://azcicontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e9ccf84870cd4b4f8c296d275f103e9c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_292949f715834ec883b74edc5ba253c4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: azcicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9ccf84870cd4b4f8c296d275f103e9c }}/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wordpressazapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_efe053bb98e74795be143940be76960c }}
        images: 'azcicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9ccf84870cd4b4f8c296d275f103e9c }}/wordpress-alpine-php:${{ github.sha }}'