# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wpappaz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_47c6ca7490b4423c9c5cc7ed68065f30 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f8f17aa9633344579b29b968003ce034 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_47c6ca7490b4423c9c5cc7ed68065f30 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wpappaz'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ab6ee56871314cba8aa3e14a608e81fe }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_47c6ca7490b4423c9c5cc7ed68065f30 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'