# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wpappaz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://azcicontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dbb7c3bbfbf849abbd5a50c1f94df001 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f710d00e8cac4a82b110741238167f96 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: azcicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dbb7c3bbfbf849abbd5a50c1f94df001 }}/wpappaz:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wpappaz'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2213f2dc85f049588e246b3087393c7e }}
        images: 'azcicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dbb7c3bbfbf849abbd5a50c1f94df001 }}/wpappaz:${{ github.sha }}'